version: "3"

services:
  database:
    container_name: ${PROJECT_NAME:-app}-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony_app}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony}
    ports:
      - "3306:3306"
    volumes:
      - ./var-lib-mysql:/var/lib/mysql

  php:
    container_name: ${PROJECT_NAME:-app}-php
    build:
      context: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/symfony_app:rw
    depends_on:
      - database

  nginx:
    container_name: ${PROJECT_NAME:-app}-nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/symfony_app:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  phpmyadmin:
    container_name: ${PROJECT_NAME:-app}-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - database
    ports:
      - 8080:80
    hostname: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER:-symfony}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-symfony}